backend:
  name: git-gateway
  branch: main

publish_mode: editorial_workflow
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Blog - posts" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
